Add bootstrap and navigation bar
Prashantneu8848/step-portfolio pull request #2
Opened 2020-05-27 14:53 UTC by Prashantneu8848

BootstrapCDN is used.

2020-05-27 15:18 UTC, Prashantneu8848 commented
Resources directory which contains images has not been added as the images for the web page are not finalized yet.

2020-05-27 16:12 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/index.html
> +                I think therefore I am - Prashant Neupane
This is definitely not my quote. I forgot to take it out. This quote is by Rene Descartes.

2020-05-28 04:17 UTC, sehtia-raghav commented on portfolio/src/main/webapp/index.html
> +                I am a Computer Science and rising Junior.
I am a Computer Science major? :P

2020-05-28 09:07 UTC, corycook requested changes

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/index.html
> +    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
Externally hosted resources are generally discouraged.

From go/htmlcssstyle#Externally-Hosted_Resources

> Avoid embedding externally-hosted scripts and stylesheets.
> 
> Embedding third-party resources can introduce a security risk if the resource owner becomes malicious or is compromised. To avoid this risk, do not embed external resources such as JavaScript, CSS stylesheets, or Flash, as they give a third party developer the ability to execute scripts in the context of your domain and access sensitive user data and cookies.
> 
> For most Google properties, even resources from some other Google-controlled domains such as Google Code hosting or internally-developed App Engine applications do not always provide sufficiently strong security guarantees and should generally be avoided. Instead, consider importing a copy of the embedded asset and host it internally; if you have any doubts about the security properties of the third-party resource, ask the security team for a review via go/getsecurityreview.

It is recommended to download these resources and store them with your code instead.

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/index.html
>      <meta charset="UTF-8">
For this and the rest of the file use 2 spaces of indentation. go/htmlcssstyle#Indentation

> Indent by 2 spaces at a time.
> 
> Don’t use tabs or mix tabs and spaces for indentation.

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/style.css
> +    height: 100vh;
For this and the rest of the file use 2 spaces of indentation. go/htmlcssstyle#Indentation

> Indent by 2 spaces at a time.
> 
> Don’t use tabs or mix tabs and spaces for indentation.

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/index.html
> +                    <a class="nav-link" href="#AboutMe">ABOUT </a>
Remove trailing space after "ABOUT"

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/index.html
> +                </li>
This may seem strange but consider omitting the closing tag for these list items. go/htmlcssstyle#Optional_Tags

> Omit optional tags (optional).
> 
> For file size optimization and scannability purposes, consider omitting optional tags. The HTML5 specification defines what tags can be omitted.

```html
<ul>
  <li class="nav-item"><a class="nav-link" href="#">HOME</a>
  <li class="nav-item"><a class="nav-link" href="#AboutMe">ABOUT</a>
</ul>
```

This makes it read more like a bullet list.

You can read about more optional tags at https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/index.html
>  <html>
Consider omitting `<html>`, `<head>`, and `<body>`. go/htmlcssstyle#Optional_Tags

> Omit optional tags (optional).
> 
> For file size optimization and scannability purposes, consider omitting optional tags. The HTML5 specification defines what tags can be omitted.

You can read about more optional tags at https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/style.css
> +#parallax {
Use specific names for element ids. go/htmlcssstyle#ID_and_Class_Naming

> Use meaningful or generic ID and class names.
> 
> Instead of presentational or cryptic names, always use ID and class names that reflect the purpose of the element in question, or that are otherwise generic.
> 
> Names that are specific and reflect the purpose of the element should be preferred as these are most understandable and the least likely to change.
> 
> Generic names are simply a fallback for elements that have no particular or no meaning different from their siblings. They are typically needed as “helpers.”
> 
> Using functional or generic names reduces the probability of unnecessary document or template changes.

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/style.css
> +#aboutMeDiv, #timelapseDiv, #picturesDiv, #connectDiv {
Use dash delimited ids and class names. go/htmlcssstyle#ID_and_Class_Name_Delimiters

> Separate words in ID and class names by a hyphen.
> 
> Do not concatenate words and abbreviations in selectors by any characters (including none at all) other than hyphens, in order to improve understanding and scannability.

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/index.html
> +            <h2 id="AboutMe">About Me </h2>
Use lowercase and dash delimited ids and class names (i.e. "about-me"). go/htmlcssstyle#ID_and_Class_Name_Delimiters

> Separate words in ID and class names by a hyphen.
> 
> Do not concatenate words and abbreviations in selectors by any characters (including none at all) other than hyphens, in order to improve understanding and scannability.

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/index.html
> +        <div id="timelapseDiv">
Just use "timelapse" without the "Div." Technically the id is independent of the particular element that it is attached to.

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/index.html
>      <meta charset="UTF-8">
```html
<meta charset="utf-8">
```

Only use lowercase (including attribute values). go/htmlcssstyle#Capitalization

> Use only lowercase.
> 
> All code has to be lowercase: This applies to HTML element names, attributes, attribute values (unless text/CDATA), CSS selectors, properties, and property values (with the exception of strings).

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/style.css
> +    background-image: url("./resources/images/landing.jpg");
Don't use quotation marks in `url()`. go/htmlcssstyle#CSS_Quotation_Marks

> Use single ('') rather than double ("") quotation marks for attribute selectors and property values.
> 
> Do not use quotation marks in URI values (url()).

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/index.html
> +                    <a class="nav-link" href="#AboutMe">ABOUT </a>
```html
<a href="#about-me">ABOUT</a>
```

Only use lowercase (including attribute values). go/htmlcssstyle#Capitalization

> Use only lowercase.
> 
> All code has to be lowercase: This applies to HTML element names, attributes, attribute values (unless text/CDATA), CSS selectors, properties, and property values (with the exception of strings).

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/style.css
> +.quotes, .hobby, .pets, .connect {
Separate each selector with a newline. go/htmlcssstyle#Selector_and_Declaration_Separation

> Separate selectors and declarations by new lines.
> 
> Always start a new line for each selector and declaration.

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/style.css
> +#parallax, #parallax1, #parallax2, #parallax3 {
Separate each selector with a newline. go/htmlcssstyle#Selector_and_Declaration_Separation

> Separate selectors and declarations by new lines.
> 
> Always start a new line for each selector and declaration.

2020-05-28 09:07 UTC, corycook commented on portfolio/src/main/webapp/style.css
> +    color: #000;
Alphabetize declarations. go/htmlcssstyle#Declaration_Order

> Alphabetize declarations.
> 
> Put declarations in alphabetical order in order to achieve consistent code in a way that is easy to remember and maintain.
> 
> Ignore vendor-specific prefixes for sorting purposes. However, multiple vendor-specific prefixes for a certain CSS property should be kept sorted (e.g. -moz prefix comes before -webkit).

2020-05-28 18:48 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/index.html
>  <html>
Done

2020-05-28 18:52 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/index.html
> +            <h2 id="AboutMe">About Me </h2>
Done

2020-05-28 18:52 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/index.html
> +                I am a Computer Science and rising Junior.
Done

2020-05-28 18:55 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/index.html
>      <meta charset="UTF-8">
done

2020-05-28 18:57 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/index.html
> +    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
I downloaded the packages using npm and hosted myself.

2020-05-28 18:58 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/index.html
> +                </li>
Done

2020-05-28 18:58 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/index.html
> +                    <a class="nav-link" href="#AboutMe">ABOUT </a>
Done

2020-05-28 19:03 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/index.html
> +        <div id="timelapseDiv">
Done

2020-05-28 19:04 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/style.css
> +    height: 100vh;
it was a built a in editor-setting.
Done

2020-05-28 19:05 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/style.css
> +#parallax, #parallax1, #parallax2, #parallax3 {
Done

2020-05-28 19:09 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/style.css
> +#parallax {
changed to background-image

2020-05-28 19:13 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/style.css
> +    background-image: url("./resources/images/landing.jpg");
Done

2020-05-28 19:13 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/style.css
> +.quotes, .hobby, .pets, .connect {
Done

2020-05-28 19:16 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/style.css
> +    color: #000;
Done

2020-05-28 19:16 UTC, Prashantneu8848 commented on portfolio/src/main/webapp/style.css
> +#aboutMeDiv, #timelapseDiv, #picturesDiv, #connectDiv {
Done

2020-05-28 19:37 UTC, Prashantneu8848 reviewed
Addressing comments from previous Review

2020-05-28 21:08 UTC, corycook approved these changes
LGTM

2020-05-28 21:15 UTC, merged